<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Defines the editing form for the programmedresp question type.
 *
 * @package    qtype
 * @subpackage programmedresp
 * @copyright 2016 Gerard Cuello (gerard.urv@gmail.com)

 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
defined('MOODLE_INTERNAL') || die();
require_once($CFG->dirroot . '/question/type/edit_question_form.php');
require_once($CFG->dirroot . '/question/type/programmedresp/lib.php');
require_once($CFG->dirroot . '/question/type/programmedresp/programmedresp_output.class.php');

/**
 * programmedresp question editing form definition.
 *
 * @copyright 2016 Gerard Cuello (gerard.urv@gmail.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class qtype_programmedresp_edit_form extends question_edit_form {
    
    // Question variables generated by qtype_linkerdescription for this quiz.
    private $linkervars;
    
    private $quizid;
    
    public function __construct($submiturl, $question, $category, $contexts,
            $formeditable = true) {
        global $DB;
        
        $cmid = optional_param('cmid', 0, PARAM_INT);
        $qtype = question_bank::get_qtype('linkerdescription', false);
        $this->quizid = '';
        if (get_class($qtype) == 'qtype_linkerdescription' && $cmid) {
            // TODO: I have to notificate this with alert or something else.
            list($quiz, $unused) = get_module_from_cmid($cmid);
            if ($qinquiz = $DB->get_records('qtype_linkerdescription', array('quiz' => $quiz->id), null, 'question')) {
                $this->linkervars = $DB->get_records_list('qtype_programmedresp_var', 'question', array_keys($qinquiz));
            } else {
                // TODO: we should advise that there isn't any linkerdescription
            }
            $this->quizid = $quiz->id;
        }
        
        // TODO: canviar estil per evitar returns
        // EPIC: Això s'hauria d'executar primer
        parent::__construct($submiturl, $question, $category, $contexts, $formeditable);

    }

    protected function definition_inner($mform) {
        global $CFG, $DB, $PAGE;
        
        $PAGE->requires->js('/question/type/programmedresp/script.js');

        // Adding wwwroot required by script.js
        // TODO: enviar directament quizid 
        echo "<script type=\"text/javascript\">//<![CDATA[\n" .
        "this.wwwroot = '" . $CFG->wwwroot . "';\n" .
        "this.quizid= '" . $this->quizid . "';\n" . 
        "//]]></script>\n";

//        var_dump($this->linkervars);
        
        // TODO: Treure $this->linkervas, ja que no s'utilitza
        $outputmanager = new prgrammedresp_output($mform, $this->linkervars);

        $editingjsparam = 'false';
        // In a new question the vars div should be loaded
        if (!empty($this->question->id)) {
            $editingjsparam = 'true';
        }

        // Button label
        if (!empty($this->question->id)) {
            $buttonlabel = get_string('refreshvarsvalues', 'qtype_programmedresp');
        } else {
            $buttonlabel = get_string('assignvarsvalues', 'qtype_programmedresp');
        }

        $varsattrs = array('onclick' => 'display_vars(this, ' . $editingjsparam . ');');
        $mform->addElement('button', 'vars', $buttonlabel, $varsattrs);

        // Link to fill vars data
        $mform->addElement('header', 'varsheader', get_string("varsvalues", "qtype_programmedresp"));

        $mform->addElement('html', '<div id="id_vars_content">');
        if (!empty($this->question->id)) {
            $outputmanager->display_vars($this->question->questiontext, $this->question->options->args);
        }
        $mform->addElement('html', '</div>');

        // Functions header
        $mform->addElement('header', 'functionheader', get_string("assignfunction", "qtype_programmedresp"));

        // Data
        $categories = $DB->get_records('qtype_programmedresp_fcat', array(), 'id ASC', 'id, parent, name');
        // Category options
        $catoptions = array(0 => '&nbsp;(' . get_string('selectcategory', 'qtype_programmedresp') . ')&nbsp;');
        if ($categories) {
            foreach ($categories as $key => $cat) {
                if (empty($catoptions[$cat->id])) {
                    $catoptions[$cat->id] = $cat->name;
                    unset($categories[$key]);
                    programmedresp_add_child_categories($cat->id, $catoptions, $categories);
                }
            }
        }
        // Category select
        $catattrs['onchange'] = 'update_addfunctionurl();return display_functionslist(this);';
        $mform->addElement('select', 'functioncategory', get_string('functioncategory', 'qtype_programmedresp'), $catoptions, $catattrs);

        // Dirty hack to add the function (added later through ajax)
        if (empty($this->question->id)) {
            $mform->addElement('hidden', 'programmedrespfid');
        }

        // Link to add a category
        $caneditfunctions = has_capability('moodle/question:config', context_system::instance());
        if ($caneditfunctions) {
            $addcategoryurl = $CFG->wwwroot . '/question/type/programmedresp/manage.php?action=addcategory';
            $onclick = "window.open(this.href, this.target, 'menubar=0,location=0,scrollbars,resizable,width=500,height=600', true);return false;";
            $categorylink = '<a href="' . $addcategoryurl . '" onclick="' . $onclick . '" target="addcategory">' . get_string('addcategory', 'qtype_programmedresp') . '</a>';
            $mform->addElement('html', '<div class="fitem"><div class="fitemtitle"></div><div class="felement">' . $categorylink . '<br/><br/></div></div>');
        }
        
        // Function list
        $mform->addElement('html', '<div id="id_functioncategory_content">');
        if (!empty($this->question->id)) {
            $outputmanager->display_functionslist($this->question->options->function->programmedrespfcatid);
        }
        $mform->addElement('html', '</div>');

        // Link to add a function
        if ($caneditfunctions) {
            $addfunctionsurl = $CFG->wwwroot . '/question/type/programmedresp/manage.php?action=addfunctions';

            // If it's a function edition we should add the selected category id
            if (!empty($this->question->id)) {
                $addfunctionsurl .= '&fcatid=' . $this->question->options->function->programmedrespfcatid;
            }

            $onclick = "window.open(this.href, this.target, 'menubar=0,location=0,scrollbars,resizable,width=650,height=600', true);return false;";
            $functionlink = '<a href="' . $addfunctionsurl . '" onclick="' . $onclick . '" target="addfunctions" id="id_addfunctionurl">' . get_string('addfunction', 'qtype_programmedresp') . '</a>';
            $mform->addElement('html', '<div class="fitem"><div class="fitemtitle"></div><div class="felement">' . $functionlink . '<br/><br/></div></div>');
        }

        // Arguments
        $mform->addElement('html', '<div id="id_programmedrespfid_content">');
        if (!empty($this->question->id)) {
            // TODO: change to array of params
            $outputmanager->display_args($this->question->options->function->id, $this->question->questiontext, $this->question->options->args, $this->question->options->vars);
        }
        $mform->addElement('html', '</div>');


        // Tolerance
        $tolerancetypes = array(
            PROGRAMMEDRESP_TOLERANCE_NOMINAL => get_string(
                    'tolerancenominal', 'qtype_programmedresp'
            ),
            PROGRAMMEDRESP_TOLERANCE_RELATIVE => get_string(
                    'tolerancerelative', 'qtype_programmedresp'
            ),
        );
        $mform->addElement('header', 'toleranceheader', get_string("tolerance", "qtype_programmedresp"));
        $mform->addElement('select', 'tolerancetype', get_string("tolerancetype", "qtype_programmedresp"), $tolerancetypes);
        $mform->addElement('text', 'tolerance', get_string("tolerance", "qtype_programmedresp"));
        $mform->addRule('tolerance', null, 'required', null, 'client');
        $mform->addRule('tolerance', null, 'numeric', null, 'client');
        $mform->setType('tolerance', PARAM_NUMBER);

        // Remove generalfeedback
        $mform->removeElement('generalfeedback');
        $mform->addElement('hidden', 'generalfeedback');
        $mform->setType('generalfeedback', PARAM_RAW);
        // Interactive settings such as penalty fields
        $this->add_interactive_settings();

        // Add the onload javascript to hide next steps
        if (empty($this->question->id)) {
            $PAGE->requires->js('/question/type/programmedresp/onload.js');
        }
    }

    /**
     * Perform an preprocessing needed on the data passed to {@link set_data()}
     * before it is used to initialise the form.
     * @param object $question the data being passed to the form.
     * @return object $question the modified data.
     */
    protected function data_preprocessing($question) {
//        debugging(__FUNCTION__);

        if (!empty($question->id)) {
            // Variables
            $varfields = programmedresp_get_var_fields();
            if ($question->options->vars['programmed']) {
                // Get only the programmed vars. The other ones (linker) don't be shown as variables
                foreach ($question->options->vars['programmed'] as $var) {
                    foreach ($varfields as $varfield => $fielddesc) {
                        $fieldname = 'var_' . $varfield . '_' . $var->varname;
                        // TODO: Clean decimals if it has ONLY 
                        $question->{$fieldname} = $var->{$varfield};
                    }
                }
            }
            // Function and function category
            $question->functioncategory = $question->options->function->programmedrespfcatid;
            // I think this is already loaded by set_data()->get_qtype_extra_fields();
            //$question->programmedrespfid = $this->options->function->id;

            // Function responses
            foreach ($question->options->responses as $returnkey => $resp) {
                $fieldname = 'resp_' . $returnkey;
                $question->{$fieldname} = $resp->label;
            }
        }
        return $question;

    }

    public function qtype() {
        return 'programmedresp';
    }

}
